### ISSUE TITLE
DL source down?

### ISSUE THREAD

**Issue by bnagy** [sign-language-processing/datasets#35]
I am running the example to load the DGS corpus, and the download fails:
`HTTPSConnectionPool(host='nlp.biu.ac.il', port=443): Max retries exceeded with url: /~amit/datasets/dgs.json`

Is this a transient failure, or a real issue (locations have changed, etc.)?

**Comment by AmitMY** [comment]
Unfortunately, the universities in Israel have been heavily attacked in the last few days.
As such, some endpoints were not available, or only available from within Israel.

To check if this works right now, you could open the following in your browser - https://nlp.biu.ac.il/~amit/datasets/dgs.json

This does show that we should move to hosting whatever file possible in a CDN not affected by possible attacks/geographic lock.

**Comment by bnagy** [comment]
OK, if it's a transient issue feel free to close this and I will just keep trying every few days / weeks :)

It's still not working at the moment (and it seems like it's not anything local to me)

Thanks for the quick response!

**Comment by AmitMY** [comment]
Should be ok now. Sorry for the late fix.
