### ISSUE TITLE
DGS Types

### ISSUE THREAD

**Issue by SerdarHelli** [sign-language-processing/datasets#39]
On DGS types, there are multi glosses corresponding one pose file. Is it possible ?

For example :

glosses=[ gloss1,gloss2,gloss3]

corresponding to one pose file according to id ?

shoul I take gloss1 ?

I am trying to create dictionary  like : 

dict={ gloss : correspondig pose , 
....}

**Comment by AmitMY** [comment]
It is possible, and you should probably take all of them.
This happens when the sign has the same form but multiple meanings.

Looking at [types](https://www.sign-lang.uni-hamburg.de/meinedgs/ling/types_de.html) you can see it: 
<img width="448" alt="image" src="https://github.com/sign-language-processing/datasets/assets/5757359/bdd82851-4e80-46fb-918a-bc8109daba54">

In this screenshot, you see `OBERFLÄCHE1` and `BEREICH1A^` are both the same form https://www.sign-lang.uni-hamburg.de/meinedgs/types/type13215_de.html

**Comment by SerdarHelli** [comment]
Also , I am gettin this error , 


config = SignDatasetConfig(name="dgs_types_poses", version="1.0.0", include_video=False, process_video=False, include_pose="holistic")
dgs_types = tfds.load('dgs_types', builder_kwargs=dict(config=config), data_dir='/content/drive/MyDrive/sing_language_datasets')


TypeError: Error while serializing feature `views/pose/data`: `TensorInfo(shape=(None, None, 1, 576, 3), dtype=float32)`: 'NoneType' object cannot be interpreted as an integer

**Comment by SerdarHelli** [comment]
> It is possible, and you should probably take all of them. This happens when the sign has the same form but multiple meanings.
> 
> Looking at [types](https://www.sign-lang.uni-hamburg.de/meinedgs/ling/types_de.html) you can see it: <img alt="image" width="448" src="https://user-images.githubusercontent.com/5757359/243343262-bdd82851-4e80-46fb-918a-bc8109daba54.png">
> 
> In this screenshot, you see `OBERFLÄCHE1` and `BEREICH1A^` are both the same form https://www.sign-lang.uni-hamburg.de/meinedgs/types/type13215_de.html

But in sample sample ,the glosses are quite different each other. Should I accept these have same pose ?

**Comment by SerdarHelli** [comment]
decode_str = lambda s: s.numpy().decode('utf-8')
c_dict=defaultdict()
for datum in tqdm(dgs_types["train"]):
    _id = decode_str(datum['id'])
    pose_file_path=f"/content/drive/MyDrive/SignLanguage/dgs_poses/{_id}_frontal.pose"
    !wget -q {pose_download_path} -P /content/drive/MyDrive/SignLanguage/dgs_poses

    pose_file_path=f"/content/drive/MyDrive/SignLanguage/dgs_poses/{_id}_frontal.pose"
    if os.path.exists(pose_file_path):
      for gloss in datum["glosses"]:
        gloss=correct_gloss(gloss)
        c_dict[gloss]=f"{_id}_frontal.pose"

**Comment by SerdarHelli** [comment]
I am doing like this

```

config = SignDatasetConfig(name="dgs_types_video", version="1.0.0", include_video=False, process_video=False, include_pose=None)
dgs_types = tfds.load('dgs_types', builder_kwargs=dict(config=config), data_dir='/content/drive/MyDrive/SignLanguage/dataset_slp')
decode_str = lambda s: s.numpy().decode('utf-8')
c_dict=defaultdict()
for datum in tqdm(dgs_types["train"]):
    _id = decode_str(datum['id'])
    pose_file_path=f"/content/drive/MyDrive/SignLanguage/dgs_poses/{_id}_frontal.pose"
    !wget -q {pose_download_path} -P /content/drive/MyDrive/SignLanguage/dgs_poses
    pose_file_path=f"/content/drive/MyDrive/SignLanguage/dgs_poses/{_id}_frontal.pose"
    if os.path.exists(pose_file_path):
      for gloss in datum["glosses"]:
          gloss=correct_gloss(gloss)
          c_dict[gloss]=f"{_id}_frontal.pose"

```

**Comment by AmitMY** [comment]
> TypeError: Error while serializing feature views/pose/data: TensorInfo(shape=(None, None, 1, 576, 3), dtype=float32): 'NoneType' object cannot be interpreted as an integer

Could you please open a different issue forthis?

> But in some samples ,the glosses are quite different each other. Should I accept these have same pose ?

This is according to the Hamburg people.  I think you should accept the same pose despite the different words.

> I am doing like this

Your code looks good to me

**Comment by SerdarHelli** [comment]
Thanks AmitMy . Yours works are amazing :)
