### ISSUE TITLE
AUTSL

### ISSUE THREAD

**Issue by aysebyz5942** [sign-language-processing/datasets#47]
ı want to download the dataset autsl for my projects(with images) (not the Tfrecord)
Where can ı found this?
thank you

**Comment by AmitMY** [comment]
The download links are here
https://github.com/sign-language-processing/datasets/blob/master/sign_language_datasets/datasets/autsl/autsl.py#L43-L50

But I would recommend using the dataset loader with `include_video=True` and `process_video=False` to get `mp4` paths on your machine to the videos. The `tfrecord` generated will be tiny, just pointing to videos.

**Comment by aysebyz5942** [comment]
Thank you for your answer. I could download the label (csv) but not the train_videos(zip) 
I am actually using windows so through the link ı couldnt use the sudo apt-get command.Do you know any solution where ı can download the dataset? Thank you in advance

**Comment by AmitMY** [comment]
It seems like the videos are no longer hosted on http://158.109.8.102/AuTSL/data/train/train_set_vfbha39.zip
You will have to contact the dataset owner to check where the updated files are.
