### ISSUE TITLE
SSL Error phoenix14t

### ISSUE THREAD

**Issue by sobek1886** [sign-language-processing/datasets#51]
Hi, when trying to download the phoenix14t dataset using this code:

``` import tensorflow_datasets as tfds
import sign_language_datasets.datasets
from sign_language_datasets.datasets.config import SignDatasetConfig

import itertools

config = SignDatasetConfig(name="no_pose", version="3.0.0", include_video=True, include_pose=None)
rwth_phoenix2014_t = tfds.load(name='rwth_phoenix2014_t', builder_kwargs=dict(config=config))

for datum in itertools.islice(rwth_phoenix2014_t["train"], 0, 10):
  print(datum['gloss'].numpy().decode('utf-8'))
  print(datum['text'].numpy().decode('utf-8'))
  print()
```

I run into

`SSLError: HTTPSConnectionPool(host='www-i6.informatik.rwth-aachen.de', port=443): Max retries exceeded with url: /ftp/pub/rwth-phoenix/2016/phoenix-2014-T.v3.tar.gz (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))`

I had the same error when trying to download the dataset in colab as well as on my local setup.
Did not run into the same issue when trying to download autsl.

**Comment by AmitMY** [comment]
Strange. If I access the URL directly, it works - https://www-i6.informatik.rwth-aachen.de/ftp/pub/rwth-phoenix/2016/phoenix-2014-T.v3.tar.gz
But if I open something like https://www.informatik.rwth-aachen.de/ftp/pub/rwth-phoenix/2016/phoenix-2014-T.v3.tar.gz it yields an insecure download
![image](https://github.com/sign-language-processing/datasets/assets/5757359/9e6e19ef-e050-4e2b-87c0-f5c262c0721a)


Can you please try now (after this commit):
https://github.com/sign-language-processing/datasets/commit/c42ff8bbd1b92fb0ceabd9a0e3ef9ded841398c8

**Comment by sobek1886** [comment]
Seems to be working now, thanks!

**Comment by cleong110** [comment]
Currently running into this again: 
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)'))': /ftp/pub/rwth-phoenix/2016/phoenix-2014-T.v3.tar.gz
```

https://colab.research.google.com/drive/1hs_UjwKv_mMxZvtittI4AD--SA6cpT5k?usp=sharing

**Comment by AmitMY** [comment]
@cleong110 are you installing from source or from pip?
maybe there should be an automated push to pip

**Comment by cleong110** [comment]
Checked the Colab notebook  to confirm and yes, from pip.
