### ISSUE TITLE
How to get the left hand, right hand, face, and pose keypoints landmarks from .pose files

### ISSUE THREAD

**Issue by SalsabilRefaei** [sign-language-processing/datasets#58]
I would be honored to have the guidance you could provide, which would be invaluable to the success of my project.
 
To be able to build the project I need Holistic and OpenPose. As you can see below I am using the autsl dataset. 

![image](https://github.com/sign-language-processing/datasets/assets/139865772/a8555e8e-cc19-4baf-8444-aadd286dcf65)

 
Loading this dataset created 3 folders for training, testing, and validation. Each folder contains the pose files for each video. (Example below)

![image](https://github.com/sign-language-processing/datasets/assets/139865772/f08be5e7-2ad3-4beb-9acc-4d4d9a8c497f)

To use these files, I tried  loading one of them as follows:
 
![image](https://github.com/sign-language-processing/datasets/assets/139865772/c41b2cac-0eea-4ce7-b1ab-40a15cff7a82)
 
What I need to be able to build the project is the key points of right hand, left hand, face, and pose for each frame. When I looked at the shape of  “numpy_data” I got the following:
 
![image](https://github.com/sign-language-processing/datasets/assets/139865772/4070d2b1-3db4-4c60-b7e4-b5a2d594d142)

When I searched for what it represents I found this:

![image](https://github.com/sign-language-processing/datasets/assets/139865772/c2de96d9-82ff-411c-8a1b-746ed5fe983b)
 
I got stuck in this stage as I did not know how to get the key points for each frame and how to get only 4 types of key points (right hand, left hand, face, pose) and to know the order of them (i.e. [[right_hand_keypoints], [left_hand_keypoints], [face_keypoints], [pose_keypoints])

**Comment by AmitMY** [comment]
If you `include_pose="holistic"` you already get that tensor as part of the dataset.

In any case, yes, you are seeing 58 frames, with 543 keypoints each, with 3 dimensions.
the `pose.header.components` specifies what components exist here (`POSE_LANDMARKS`, `FACE_LANDMARKS`, `LEFT_HAND_LANDMARKS`, `RIGHT_HAND_LANDMARK`) with 33, 468, 21 and 21 keypoints.
So, to get the face for example, you need to `pose.body.data[33:33+468]`

**Comment by cleong110** [comment]
Out of curiosity: Those 543 landmarks were mostly generated with [this version of Holistic](https://github.com/google/mediapipe/blob/master/docs/solutions/holistic.md), right? The one that Google is now calling "legacy"? https://developers.google.com/mediapipe/solutions/vision/holistic_landmarker. The documentation lines up:
> the task outputs a total of 543 landmarks (33 pose landmarks, 468 face landmarks, and 21 hand landmarks per hand) in real-time.

**Comment by cleong110** [comment]
OK, trying to understand this in more detail, I've made a Colab Notebook to experiment a bit: https://colab.research.google.com/drive/1xYZWaYA0lmvnKNJnght3YdLZA7X_xWcX?usp=sharing

I THINK I've made a procedure for calculating the proper indexes:

```python
index = 0

print(f"Pose Components for AUTSL (Holistic): {[pose_component.name for pose_component in pose_data.header.components]}")

for pose_component in pose_data.header.components:
  component_length = len(pose_component.points)
  start_index = index
  end_index = start_index + component_length
  print(f"{pose_component.name} has {component_length} keypoints")
  print(f"start_index:  {index}")
  print(f"end_index (inclusive): {end_index-1}")
  print(f"end_index (exclusive): {end_index}")

  print(f"Slicing syntax includes the first index but not the second, ")
  print(f"and https://pose-format.readthedocs.io/en/latest/_modules/pose_format/pose_body.html defines pose body data as")
  print(f">Data in the format (Frames, People, Points, Dims) e.g., (93, 1, 137, 2)")
  print(f"So you can access {pose_component.name} with \n\tpose_data.body.data[frame_index][person_index][{start_index}:{end_index}]")
  index = end_index
  print()
```

so tl;dr you can access
```
POSE_LANDMARKS with 
	pose_data.body.data[frame_index][person_index][0:33]
FACE_LANDMARKS with 
	pose_data.body.data[frame_index][person_index][33:501]
LEFT_HAND_LANDMARKS with 
	pose_data.body.data[frame_index][person_index][501:522]
RIGHT_HAND_LANDMARKS with 
	pose_data.body.data[frame_index][person_index][522:543]

**Comment by cleong110** [comment]
So then 
```
frame_zero_person_zero_left_hand = pose_data.body.data[0][0][522:543]
frame_zero_person_zero_left_hand.shape # (21, 4)
```

**Comment by cleong110** [comment]
... or there's get_components, which I just realized exists: 
```
pose_data.get_components(["RIGHT_HAND_LANDMARKS"]).body.data.shape # (80, 1, 21, 4)
```

**Comment by cleong110** [comment]
So the easy solution in the end for you might just be

```
pose = Pose.read(data_buffer)
left_hand_landmarks = pose_data.get_components(["LEFT_HAND_LANDMARKS"])
right_hand_landmarks = pose_data.get_components(["RIGHT_HAND_LANDMARKS"])
# etc

```

**Comment by cleong110** [comment]
Or like this: 
```
keypoints_for_each_component_dict = {}
for component in pose_data.header.components:
  keypoints_for_each_component_dict[component.name] = pose_data.get_components([component.name])

for key in keypoints_for_each_component_dict.keys():
  print(f"{key} keypoints have shape: {keypoints_for_each_component_dict[key].body.data.shape}")
```

![image](https://github.com/sign-language-processing/datasets/assets/122366389/a083aa26-30ad-4d6d-8556-7b2ca89822dd)

**Comment by SalsabilRefaei** [comment]
> If you `include_pose="holistic"` you already get that tensor as part of the dataset.
> 
> In any case, yes, you are seeing 58 frames, with 543 keypoints each, with 3 dimensions. the `pose.header.components` specifies what components exist here (`POSE_LANDMARKS`, `FACE_LANDMARKS`, `LEFT_HAND_LANDMARKS`, `RIGHT_HAND_LANDMARK`) with 33, 468, 21 and 21 keypoints. So, to get the face for example, you need to `pose.body.data[33:33+468]`

Is it 3 or 4 dimensions? because when I try seeing the data points of one frame what I get is an array with 4 elements 
![image](https://github.com/sign-language-processing/datasets/assets/139865772/0e7f24a8-a564-433e-bb9d-f3ee6a4505b0)
what I expected is an x, y, z coordinates but if it is 4 dimensions then what does this data represent?

**Comment by cleong110** [comment]
Confidence I would guess? 

![image](https://github.com/sign-language-processing/datasets/assets/122366389/fb48502b-becb-40d5-919a-823790d25a8e)

**Comment by cleong110** [comment]
![image](https://github.com/sign-language-processing/datasets/assets/122366389/e87cbb09-0430-4683-b152-086f19f28aed)

**Comment by AmitMY** [comment]
In AUTSL and AUTSL alone, there are 4 dimensions: X, Y, Z, and K where K the depth value from Kinect since it was available

**Comment by cleong110** [comment]
I think the question is answered, and we can close this issue. It might be good to add a section to the docs answering the question based on all this.
