### ISSUE TITLE
How to download the Spread the Sign Dataset?

### ISSUE THREAD

**Issue by Jai2500** [sign-language-processing/datasets#78]
Hello, 

I'm trying to download the Spread the Sign dataset (Holistic poses) using the library, but I get the error that `pose_dir` and `csv_path` are not defined. Where do I get those files? 

Best,
Jai

**Comment by AmitMY** [comment]
SpreadTheSign has a restrictive license, and does not allow using their data.
Therefore, this data loader can only be used by people with explicit approval and download of the data.
Sorry for not having better news.
